version: '3.8'

services:
  ja4-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: ja4_container
    volumes:
      - ./src:/app       # Mount the 'src' directory for your Python files
    tty: true
